addon/components/es-form/es-label.js, addon/components/es-form/es-select.js, app/components/es-form/es-label.js, app/components/es-form/es-select.js, yarn.lock
I saw when I first forked the project, failing test-cases. So fixed them and there is one more integration test which is failing `{{es-navbar}}`.
=> Fixed the wrong reference to layouts for es-label & es-select components

addon/components/es-navbar/template.hbs, package-lock.json, tests/integration/components/es-navbar/component-test.js
this allows us to pass in the search component using https://github.com/ember-learn/ember-learn-search-components 
Example of this in use for the Guides-App: https://github.com/ember-learn/guides-app/pull/50/files#diff-f63965ba48df687541db46e0e1b2c2ecR10
(I manually rebased this to make sure that it would work with the big merge that happened recently)
=> add ability to pass search component into navbar via yield

addon/templates/components/es-footer.hbs, tests/integration/components/es-footer-test.js, yarn.lock
This PR removes the Google plus link from the footer. That page isn't active and has a bit of spam.
Note: The lock file changed on fresh install, but I think that's ok with yarn.
=> Remove google plus link

addon/components/es-button.js, addon/styles/_es-button.scss, tests/dummy/app/templates/docs/components/es-button.md, tests/dummy/app/templates/index.md, tests/integration/components/es-button-test.js
- removed 'isLight' property- it should be considered light if the isDark property is set to false, so we don't need both. 
- changed 'disabled' to 'isDisabled' for consistency and updated the areas where it should be updated
- removed 'ariaDescribedBy' property since you wouldn't need one of those for a button. If someone can present a valid use case then I'm happy to have it added back in. 
Still need to (will do these in another PR):
- re-visit the icon thing so more PRs for this component may be required. 
- figure out what the dataRole property is supposed to be for
- add some more example use cases to the documentation
=> updated the button component and supporting documentation 

ember-cli-build.js, index.js
This change removes the app requirement to configure the `ember-cli-bootstrap` addon to make `ember-styleguide` works.
This change is part of the ongoing work to use the addon on ember-learn/ember-help-wanted#17
If this is merged, the `ember-cli-bootstrap` configuration at the [guides-app](https://github.com/ember-learn/guides-app/blob/master/ember-cli-build.js#L26) could be removed.
Could someone enumerate the projects using `ember-styleguide`?
=> Configure automatically the `ember-cli-bootstrap` addon

addon/components/es-footer.js, addon/components/es-footer/es-contributions.js, addon/components/es-footer/es-info.js, addon/components/es-footer/es-statement.js, addon/constants/es-footer.js, addon/styles/_es-footer.scss, addon/templates/components/es-footer.hbs, addon/templates/components/es-footer/es-contributions.hbs, addon/templates/components/es-footer/es-info.hbs, addon/templates/components/es-footer/es-statement.hbs, app/components/es-footer/es-contributions.js, app/components/es-footer/es-info.js, app/components/es-footer/es-statement.js, package-lock.json, tests/dummy/app/controllers/docs/components/es-footer.js, tests/dummy/app/data/footer.js, tests/dummy/app/templates/docs/components/es-footer.md
Implements #56
The component has been extended to support a few cases. 
```
{{es-footer }}
```
```
{{es-footer tagline="A framework for ambitious web developers"}}
```
```
{{#es-footer as |f|}}
{{f.info infoLinks=infoLinks}}
{{f.statement socialLinks=socialLinks}}
{{f.contributions contributorLinks=contributorLinks}}
{{/es-footer}}
```
```
{{#es-footer as |f|}}
{{#f.info}}
<br/>
<a>Team</a>
<br/>
<a>Contact</a>
{{/f.info}}
{{#f.statement}}
Highly Productive Out of the Box
{{/f.statement}}
{{#f.contributions}}
<div class="contributor">
<p>Hosted by:</p>
<a href="https://www.heroku.com/emberjs">
{{svg-jar "heroku-logo" class="contributor-logo"}}
</a>
</div>
{{/f.contributions}}
{{/es-footer}}
```
The addon documentation has been included. I wait for feedback to modify the API and/or improve …
=> Footer: separate data from the component

index.js
This change allows apps to import `ember-styleguide sass` modules like:
```
@import "ember-styleguide/globals/variables";
```
This case was discussed at EndangeredMassa/ember-help-wanted#6
cc @MelSumner @EndangeredMassa
=> Export `sass` modules on `ember-styleguide` namespace

index.js
Publishing the addon with isDevelopingAddon to true causes undesirable things such as an app's linting evaluating styleguide addon files (which is happening with ember-api-docs right now).
=> Set isDevelopingAddon to false

index.js
This check for ember-cli-sass is causing a crash in the build when an **addon** depends on ember-styleguide (as opposed to an app directly)
This change doesn't change any functionality as it's wrapping a console log 👍
=> prevent crash when addon depends on ember-styleguide

addon/components/es-navbar/component.js, addon/components/es-navbar/template.hbs, addon/constants/links.js, tests/dummy/app/controllers/docs/components/es-navbar.js, tests/dummy/app/templates/docs/components/es-navbar.md
This is a backwards compatible change that allows for default links to be provided by the ember-styleguide. 
This prevents every consuming app from needing to define the links but allows them to define them if the need/want to. It also exposes the default links for import so consuming apps can make small changes to the links object instead of it being "all or nothing" 👍
=> Implementing default links for the navbar

addon/constants/links.js
I have added the CLI guides to the "Docs" dropdown, and clarified "The Guides" as "Ember.js Guides".
I did not add a link to the CLI Guides API because I think it's ok for someone to get to it via the Guides. The CLI API docs also need some kind of review before they are included in the top navbar.
"The Guides" are really "The Ember.js Guides" because as we make more guides (like Ember Data, Ember CLI, etc) we need more granular descriptions.
These 3 PRs should be merged at the same time:
1. ember-styleguide https://github.com/ember-learn/ember-styleguide/pull/115
2. ember-api-docs https://github.com/ember-learn/ember-api-docs/pull/576
3. website https://github.com/emberjs/website/pull/3705
=> Add CLI Guides to the default navbar links

addon/constants/links.js
This fixes an issue with the default links.
Before: 
After:
=> replacing &rarr; with →

addon/components/es-navbar/link/component.js
This is something that is causing a few issues when starting an app as a result of merging #77 
I'm not entirely sure why this didn't show up in the tests for ember-styleguide 🤔 and I'm also not 100% sure why this isn't breaking Percy on the new website with this PR: https://github.com/ember-learn/ember-website/pull/135
Something strange is going on but this PR is required to fix the issues. We shouldn't be accessing the element before the element is added to the dom
=> Fixing issue with element not being available when setting tabIndex

addon/components/es-navbar/template.hbs
I think this was something that was lost in the navbar update. This fix is needed for the default links to still be in effect 👍
=> Fixing default links

addon/styles/_es-navbar.scss
This is a simple fix that prevents a small bug in the new navbar. It is best illustrated in a screenshot: 
Before: 
After:
=> es-navbar: hide menu items when navbar is closed

addon/services/navbar.js
As discussed with @mansona offline this is required for fixing https://github.com/ember-learn/ember-website/issues/151
The PR introduces a `closePopupMenu` method to the `navbar` service. This allows you to close the `es-navbar` dropdown if it's open.
```js
this.navbar.closePopupMenu();
```
I was trying to add a unit test for the new function but it wasn't straightforward. It's a bit janky as internally the `navbar#register` method accesses the DOM which isn't available in a unit test. Any thoughts?
=> Add closePopupMenu function to navbar service

addon/components/es-navbar/template.hbs
https://dequeuniversity.com/rules/axe/2.2/button-name?application=lighthouse
Address automated audit failure about empty button with no contents.
We could improve this further, but we have no reason not to at least add a label here.
=> Comply with axe-core 2.2

addon/constants/links.js
The new ember-website app uses slightly different URLs for the legal and releases pages. The app performs some URL translations (in the application controller) to convert the old legal and releases URLs to the new ones. This edit will update the old links so that the URL translations in the app will no longer be required and thus can be removed in the future.
=> Update legal and releases links

.travis.yml, addon/templates/components/es-footer.hbs, package.json, tests/dummy/app/templates/docs/components/es-footer.md, tests/integration/components/es-footer-test.js, yarn.lock
This PR converts `{{es-footer}}` component to `<EsFooter/>`. #123 
**Note**: This PR also adds [ember-angle-bracket-invocation-polyfill](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill), so we can continue supporting `2.16` and `2.18` versions.
=> [#123] / Convert es-footer to be an angle bracket component

addon/constants/links.js
Sister PR with https://github.com/ember-learn/ember-website/pull/351
Should only be merged and released after that PR.
I changed the page name to "Overview" because "Channels" doesn't describe the content anymore.
=> Add lts to builds in the navbar

addon/styles/helpers.css, addon/styles/layout.css, docs/concepts/colours.md, docs/concepts/layout.md, tests/dummy/app/templates/components/color-pallet.hbs
This PR replaces the flexbox based layout classes with css grid in order to reduce the amount of divs needed to create the pages.
=> change flexbox to grid

addon/components/es-ulist.js
Currently `{{es-ulist}}` is being used in **none** of the apps that depend on the ember-styleguide. This PR deprecates the use of es-ulist and allows us to remove it in the [website-redesign-rfc branch](https://github.com/ember-learn/ember-styleguide/pull/145)
Closes https://github.com/ember-learn/ember-styleguide/pull/130
=> deprecating es-ulist

addon/components/es-navbar.js, addon/components/es-navbar/link/component.js, addon/components/es-navbar/link/template.hbs, addon/styles/components/es-navbar.css, addon/templates/components/es-navbar.hbs, docs/components/navbar.md, docs/concepts/accessibility.md
This PR is a git-fu splitting of https://github.com/ember-learn/ember-styleguide/pull/188 to only include the things that affect the navbar
This will probably need a bit more of an adjustment before it is ready to be merged
Closes https://github.com/ember-learn/ember-styleguide/pull/188
=> Resolve accessibility issues with the navbar

README.md, addon/components/es-pagewrapper.js, tests/dummy/app/templates/docs/components/es-pagewrapper.md, tests/dummy/app/templates/docs/components/es-ulist.md
This PR is similar to https://github.com/ember-learn/ember-styleguide/pull/200 
I just want to deprecate the use of `{{es-pagewrapper}}` so that I can remove it from the next version of the styleguide 👍 
Note: it is not used anywhere in an app consuming the styleguide
=> Deprecate es pagewrapper

addon/styles/global.css, addon/styles/typography.css, docs/concepts/colours.md, docs/concepts/typography.md
this PR closes #211 
It also includes some adjustments to typography proportion and spacing to improve legibility of blocks of text.
=> improve typography and color docs

addon/templates/components/es-note.hbs
Now, all images with a presentation role have an empty `alt` text.
=> Removed alternate text for es-note component, which will show Zoey or Tomster image

addon/components/es-navbar.js, addon/styles/components/es-navbar.css
Fixing a slight list item anomaly in the nav bar: 
(I'm not entirely sure why that isn't there in the styleguide 🤔 )
And reverting something that shouldn't have made it into my previous PR: https://github.com/ember-learn/ember-styleguide/pull/219#discussion_r331967751
=> Small navbar fixes

addon/styles/background-shapes.css, docs/concepts/background-shapes.md, public/images/swipe-top.svg
This is a small change to the way swipe-top works, it is now pinned to the bottom left of the section that it is applied to.
This gives you more control over where the "swipe" actually goes and what it covers 👍
=> fix background swipe-top

addon/styles/colors.css, addon/styles/helpers.css, docs/components/page-header.md, docs/concepts/background-shapes.md, docs/concepts/layout.md, docs/css/helpers.md
This PR will add the css helpers needed to implement the website design.
=> Css Helpers

addon/styles/components/es-header.css, addon/styles/global.css, addon/styles/layout.css
This also introduces appropriate variables for the spacing and moves the container declaration into a single place.
Closes #231
=> Add outside spacing for containers on mobile

addon/styles/background-shapes.css, addon/styles/colors.css, addon/styles/components/es-button.css, addon/styles/components/es-card.css, addon/styles/components/es-footer.css, addon/styles/components/es-header.css, addon/styles/components/es-page-header.css, addon/styles/global.css, addon/styles/helpers.css, addon/styles/layout.css, addon/styles/typography.css, addon/templates/components/es-page-header.hbs, docs/concepts/background-shapes.md, docs/concepts/colours.md, docs/concepts/layout.md, docs/css/helpers.md, docs/css/icons.md, tests/dummy/app/styles/app.css, tests/dummy/app/styles/color-pallet.css
There is no issue for this PR, but it was necessary to formalize the grayscale palette and other things.
=> Update and cleanup CSS variables and related helpers

addon/templates/components/es-card.hbs
Currently, there's not a way to set the built-in `<img>` tag's `role` attribute for `<EsCard>` component. If we directly pass `role="presentation"` to the `<EsCard>` declaration, the role gets set on the `<li>` tag instead.
=> Add presentation role to image in es-card if its alternate text is empty string

addon/styles/addon.css, addon/styles/background-shapes.css, addon/styles/components/es-footer.css, addon/styles/components/es-header.css, addon/styles/container.css, addon/styles/flex.css, addon/styles/global.css, addon/styles/grid.css, addon/styles/layout.css, docs/components/card.md, docs/concepts/background-shapes.md, docs/concepts/colours.md, docs/concepts/layout.md
I had a bit of trouble with this one, as most of its changes are entangled into each other, which made it hard to separate. 
This replaces the previously available `.layout-grid` class into two separate helpers, one for `.layout` which allows for lay outing content in an editorial way (columns, reordering, skipping columns) and `.grid`, which provides a very clean way to displaying a list of similar contents (think logos, cards, …) in an equally spaced grid.
Closes #237  (no longer required, now a basic feature of `.layout`)
Re #235 (we still need much more documentation, but I ran out of time for today)
This also revisits all font sizes and vertical rhythms and increases the font size for desktop user to 16px. It also changes the base unit for `1rem` to the browser default of 16px as I …
=> Sizes, layout and grids

addon/styles/helpers/index.css
This is adding `!important` to the `.hide-on-mobile` helper so that it can override any display attributes on application css 👍
=> make hide-on-mobile !important

addon/styles/components/es-card.css, docs/components/card.md
The hover state of the card on a light background was fine but we need a different shade when on a dark background.
Before: 
After:
=> Fix dark card hover

addon/styles/global.css, public/images/swipe-top.svg
This is only fixing the colour contrast for secondary buttons. I also added a tiny fix to remove a stray "dot" in the swipe-top svg while I was here
=> Fix axe warnings

docs/components/card.md, docs/components/link-card.md
This just adds the docs update that was missing from https://github.com/ember-learn/ember-styleguide/pull/279
=> Add docs for the new Cards API

addon/styles/components/es-footer.css, addon/templates/components/es-footer.hbs, addon/templates/components/es-footer/es-contributions.hbs, addon/templates/components/es-footer/es-info.hbs, addon/templates/components/es-footer/es-statement.hbs
This implements the new design for the footer. Here are some screenshots for ease of review: 
Fixes https://github.com/ember-learn/ember-website/issues/548
=> Implement the new design for the Footer

index.js
Having `isDevelopingAddon` set to true when we publish the package causes template errors to show up on the consuming app's build output. 
Resolves #289.
=> Remove isDevelopingAddon from the addon config

package-lock.json, package.json
This fixes an issue with failures on 3.19+ due to the removal of a private API deprecation (modifier managers not having a `capabilities` field).
=> Update @ember/render-modifiers to 1.0.2.

package-lock.json, package.json
This is a tiny oversight on my part 🙈 
Essentially we made sure that the new ember-styleguide worked all the way to Ember 3.8 (tested with ember-try) but for older pre-octane apps that don't have `@glimmer/component` installed in their package.json we would need to provide it as a dependency. 
This was missed because of the fact that dev-dependencies are included when running tests from an addon directly 🙃 I don't know if this is something that we should discuss with the ember-cli team to see if there is a better default 🤔 
This also more accurately represents the dependencies of this addon anyway 👍
=> make sure @glimmer/component is a dependency for older Ember versions

package-lock.json, package.json, tests/dummy/config/environment.js
This fixes the tag line under the logo, changes it from `Ember Field Guide` to `Ember Styleguide` 🎉 
Fixes #314
=> Fix the "tag line"

docs/concepts/colors.md, docs/concepts/typography.md
Fixes https://github.com/ember-learn/ember-styleguide/issues/309.
=> Update spelling to use American English

addon/components/es-header.js, addon/styles/components/es-header.css, addon/templates/components/es-header.hbs, tests/integration/components/es-header-test.js
- Update the component to use Ember Octane API.
- Remove the code for reseting `expanded` on CSS breakpoints for
a more predictable behaviour and prevention of memory leaks.
- Add `navbar-expanded` class to simplify styles and reduce coupling
with HTML structure.
- Fix accessibility warnings.
- Add additional tests.
=> Simplify `EsHeaderComponent` implementation.

.travis.yml
The test system has suddenly stopped working because we have a very out dated Chrome install. This is because of https://travis-ci.community/t/you-can-no-longer-install-chrome-stable-on-trusty-machines/8521
We just need to use the default that travis provide (by removing the trusty config)
=> fix the build

index.js, package-lock.json, package.json
- a bug was introduced by [changes in ember-cli 3.18](https://github.com/ember-cli/ember-cli/pull/9183/files) that affected loading of styleguide styles in an app consuming styleguide that used ember-cli 3.18+
- the [static-postcss-addon-tree package](https://github.com/empress/static-postcss-addon-tree) was created to solve for this
Closes: #330
=> Introduce static-post-css-addon-tree

addon/styles/global.css, docs/concepts/colors.md
Add the secondary colour pallet as defined in the Abstract
https://deploy-preview-305--ember-styleguide.netlify.app/concepts/colours/
=> Secondary colors

index.js
I'm not entirely sure what is going on here but the floating dependency check on empress-blog-ember-template is failing because of this issue 🙃  https://travis-ci.org/github/ember-learn/empress-blog-ember-template/jobs/706485322
Something changed but I'm not sure what. I'm going to release this pretty quickly to unblock the blog work, but we should probably get to the bottom of the issue at some point
=> fix issue with building addons

addon/styles/global.css
- h4 and h5 were not being distinguished from regular text in a meaningful way as described in https://github.com/ember-learn/ember-styleguide/pull/335
- this attmepts to fix the size and weight of these styles
Co-Authored-By: Chris Manson <mansona@users.noreply.github.com>
=> h4 and h5 style fixes

addon/styles/global.css
- images in markdown breakout of their container as described in https://github.com/ember-learn/ember-styleguide/pull/335
- this sets a max width to constrain them
Co-Authored-By: Chris Manson <mansona@users.noreply.github.com>
=> fix image constraints

index.js
this reduces the number of fonts that someone would download to only include the one they are most likely to be using 👍
=> only preload variable font

addon/constants/links.js
The Ember jobs board provided a valuable source of revenue to the
project for a long time. However, today the steering committee finds
that it is rarely the best place to find work in Ember, and additionally
that offerings like OpenCollective have largely supplanted its role in
generating (very modest, trust me) revenue.
As such, we're removing it from the website header. This doesn't
preclude adding new content about "Finding a Job in Ember" at some
point in the future, but in the short term we want to start the process
of mothballing the current jobs site.
=> Drop jobs.emberjs.com from the community menu

app/templates/components/es-navbar.js
This seems to be a leftover file that's unused. When running in its most-compatible mode, embroider will try to pick this file up and error because it contains a broken import statement.
=> fix broken import from unused file

docs/components/button.md
Replace `something` with "`es-button` or `es-button-secondary`"
Fixes #351
=> Update CSS class name in `button` documentation

addon/constants/links.js
Practically speaking the RFC Tracking project has not been in use for some quite.
Linking to it does the project a disservice as it paints a picture of inactivity which is not accurate.
=> Remove RFC tracking link

addon/constants/links.js
this enables prettier for the links file so that we can follow up and change some links in another PR
=> Enable prettier for links file

addon/styles/sidebar-container.css, tests/integration/components/es-sidebar-test.js
The current width that was set a long time ago for the Blog implementation of the sidebar is not suitable for for example the guides. It also improves display of the sidebar in the Blog in case of long titles (e.g. ember times).
=> make sidebar wider to better match its contents' requirements

addon/styles/global.css, docs/concepts/markdown.md
Closes #380 
Merging this PR fixes a problem where the Ember Blog has no styling for inline code. The only clue that they are code is the monospace font.
Previously, there was zero contrast on these elements. This current attempt could use some accessibility improvements, but it could be merged as a stop gap.
=> Add a background color to inline code

package-lock.json, package.json, tests/dummy/config/targets.js
This should address the issue with https://github.com/ember-learn/ember-styleguide/issues/386 
I also needed to bump the ember-source version because there was a patch version of 3.25 that fixed an underlying issue of the ember-source code not transpiling correctly for fastboot https://github.com/emberjs/ember.js/pull/19397
I have verified that this fix does solve the issue locally 👍 
Closes https://github.com/ember-learn/ember-styleguide/issues/386
Closes https://github.com/ember-learn/ember-styleguide/pull/387
=> Add node: current to targets for dummy app

addon/styles/sidebar-container.css, tests/integration/components/es-sidebar-test.js
edit: this is no longer a work in progress, this actually **successfully** converts the flexbox sidebar implementation to grid 🎉 
It was a bit tricky to figure out but myself and @jaredgalanis got there in the end 💪  Thanks also to @jenweber for the initial help (and links to cheatsheets) 
Fixes: https://github.com/ember-learn/ember-styleguide/issues/389
=> start using CSS grid for sidebar implementation

addon/services/progress.js
This is fixing the htmlSafe import as described here https://deprecations.emberjs.com/v3.x#toc_ember-string-htmlsafe-ishtmlsafe
I think this is also causing issues in Ember 3.27 because of module issues 🤔
=> fix htmlSafe import

addon/constants/es-footer.js
Sadly https://www.heroku.com/emberjs is now a 404
=> Fix Heroku footer link

addon/components/es-note.hbs, addon/styles/components/es-note.css, package-lock.json
fixes: https://github.com/ember-learn/ember-styleguide/issues/405
=> Use CSS instead of utility classes from ESNote - to allow HTML to be backwards compatible

addon/components/es-banner.hbs, addon/styles/addon.css, addon/styles/components/es-banner.css, app/components/es-banner.js, docs/components/banner.md, tests/integration/components/es-banner-test.js
Fixes #371
This implements the banner in the same way it's currently implemented on the website. The only difference is that the banner is **dismissible** on mobile. Because I thought it weird that that should not be the case.
=> Creates banner with the same style as on the current website

.github/workflows/ci.yml
So... turns out github action permissions are quite complicated 🙈 it seems like the `continue-on-error-comment` thing that should be working for all PRs isn't allowed to be used for dependabot. 
You can see that it's failing here: https://github.com/ember-learn/ember-styleguide/actions/runs/4346537705/jobs/7592840959 with the message: 
```
Error: Resource not accessible by integration
```
I did some investigation and it looks like this change should fix it, but it's going to be a bit trial and error 🤷 
Edit: It still failed with 
```
permissions:
issues: write
```
but now works with 
```
permissions:
pull-requests: write
```
so I think this is going to work 👍 I'll merge this and rebase a dependabot PR and we'll see if it fixes it
=> add permissions for continue-on-error

addon/styles/global.css
The font-size did change with mobile, but the margin on the `<hr>` it did not, resulting in weird distances
=> Fix mobile margin for <hr>

config/ember-try.js
ember-release was failing because of this, previously already added for beta and canary.
Maybe we should consider adding it to the default dependencies, since we'll only be getting this more from here on out.
=> Add @ember/string to ember-release dependencies

addon/constants/links.js
We noticed the menu is out of sync between ember-website and the rest of the apps relying on style guide's menu constant directly.
We should probably only manage the menu in styleguide itself. This is step 1 for that, to bring the menus back in sync.
After this is merged and released we can (figure out how to) update styleguide for ember-website and remove the customisation.
=> Sync menu content from ember-website to styleguide

addon/styles/addon.css, addon/styles/central-content.css, addon/styles/on-this-page.css, docs/concepts/central-content.md, docs/concepts/on-this-page.md
=> Central content + on-this-page styling

addon/styles/components/es-sidebar.css, addon/styles/sidebar-container.css, tests/integration/components/es-sidebar-test.js
This moves some of the tweaks that we were doing in https://github.com/ember-learn/guidemaker-ember-template "upstream" into styleguide 👍 
Edit: This is a breaking change because any consumers of `<EsSidebar />` that didn't want to have a grey background will need to add `.bg-light` or reset the style themselves 👍
=> make sidebar content slightly wider and add background colour

addon/styles/global.css
Small tweak to make the inline code backticks more readable and easier to scan on the page.
=> style: lighten backtick style
