- .stylelintrc.js
- package.json
This will enforce:
* No ids
* Lowercase selectors
* Colors must use variables
* Variables must be lowercase and dasherized
* Alphabetical order for properties
We may want to add some things, but this is hopefully a good first pass.
> Add initial stylelint rules

- addon/components/es-button.js
- addon/styles/_es-button.scss
- addon/styles/variables.scss
- addon/templates/components/es-button.hbs
- package-lock.json
- package.json
- tests/integration/components/es-button-test.js
> Base es-button component

- addon/components/es-note.js
- addon/constants/mascots.js
- addon/styles/_es-note.scss
- addon/styles/addon.scss
- addon/templates/components/es-note.hbs
- app/components/es-note.js
- package-lock.json
- package.json
- tests/integration/components/es-note-test.js
> Build base es-note component

- addon/styles/_es-navbar.scss
@rwwagner90 I think this should do it. 
Should address https://github.com/ember-learn/ember-styleguide/issues/3
> fixing navbar on mobile

- tests/integration/components/es-navbar-test.js
- tests/integration/components/es-navbar/component-test.js
- ugh I'm sorry about this
- making the tests pass for now
- https://github.com/ember-learn/ember-styleguide/issues/29 will track this issue
> making the navbar tests pass

- addon/templates/components/es-footer.hbs
- package-lock.json
- tests/dummy/app/data/navbar-links.js
This change corresponds with https://github.com/emberjs/website/pull/3381
> Changes "Logos" link to "Brand"

- addon/styles/addon.scss
- addon/styles/globals/_helpers.scss
- addon/styles/globals/_typography.scss
- moved helpers to their own file (globals/helpers) 
- imported it into the addon.scss
- updated styles that were problematic
> resolves issues in #71

- addon/templates/components/es-footer.hbs
- package-lock.json
Fixes https://github.com/ember-learn/guides-source/issues/91
> Hard code to full url paths

- addon/components/es-blog-heading.js
- addon/constants/es-blog-heading.js
- addon/styles/_es-blog-heading.scss
- addon/templates/components/es-blog-heading.hbs
- tests/dummy/app/templates/docs/components/es-blog-heading.md
- tests/integration/components/es-blog-heading-test.js
- made it simpler
- added some more examples in the docs
- removed tests that weren't necessary anymore
> updated the blog header component to remove unnecessary complexity

- tests/dummy/app/templates/docs.md
- tests/dummy/app/templates/docs/index.md
- updated the site sections
- updated info on the home page to be more complete
> updating site sections and updated info on homepage

- tests/dummy/app/templates/docs/components/es-buttonbar.md
- tests/integration/components/es-buttonbar-test.js
> use angle-bracket syntax for es-buttonbar component

- addon/components/es-navbar/link/component.js
fixes: https://github.com/ember-learn/ember-website/issues/152
> fixing z-index of dropdown

- addon/components/es-navbar/link/component.js
- addon/styles/_es-header.scss
- addon/styles/_es-navbar.scss
Fixing a number of issues with the navbar that @Turbo87 noticed 🎉 we paired together to fix them 👍
> Navbar tweaks

- addon/constants/es-footer.js
- addon/templates/components/es-footer/es-contributions.hbs
This pr is for [#148](https://github.com/ember-learn/ember-styleguide/issues/148)
Please see the accessibility audit result with this fix.
> fixing accessibility bugs on navbar toggle button and footer links

- package.json
- yarn.lock
After this is merged, we can rebase https://github.com/ember-learn/ember-styleguide/pull/126 and CI / ember-try should pass.
> Add ember-angle-bracket-invocation-polyfill

- tests/dummy/app/templates/docs/components/es-note.md
- tests/integration/components/es-note-test.js
> use angle-bracket syntax for es-note component

- tests/dummy/app/templates/docs/components/es-blog-heading.md
- tests/integration/components/es-blog-heading-test.js
> use angle-bracket syntax for es-blog-heading component

- addon/styles/components/es-navbar.css
- addon/templates/components/es-navbar.hbs
This PR aims to simplify styling for the navbar and apply the standard size units to all elements.
> Style navigation component

- addon/styles/addon.css
- addon/styles/global.css
- addon/styles/helpers.css
- addon/styles/typography.css
- tests/dummy/app/templates/concepts/typeography.md
This PR adds the needed typography styles needed to build https://github.com/ember-learn/ember-website/issues/315
> Add typography styles

- addon/constants/links.js
> [Doc] Update the Help Wanted link in nav bar

- addon/styles/addon.css
- addon/styles/components/es-card.css
- addon/styles/helpers.css
- addon/styles/layout.css
- addon/styles/typography.css
- tests/dummy/app/templates/concepts/layout.md
This PR contains the classes needed to implement the content on https://github.com/ember-learn/ember-website/issues/315
> Layout classes

- addon/components/es-navbar/link/template.hbs
- package.json
> patch release for #183

- .travis.yml
- docs/concepts/colours.md
This is just a quick temporary fix for the colour page while we're still figuring out how to get `col-one-third` to degrade correctly for smaller screen sizes 👍 
I also hopefully fixed the issue where Percy would run for every ember-try scenario 🙈
> Fixing colours

- addon/styles/global.css
> Set body and text color

- addon/styles/global.css
- addon/styles/typography.css
- index.js
I created some issues with the bold weights when using the variable font because I wanted to be clever. This fixes me being clever and actually makes the semibold fonts work as expected.
> Inter fixes

- addon/styles/global.css
> Add underlines back

- addon/styles/helpers.css
- docs/css/helpers.md
> Helper for responsive video embeds

- addon/styles/addon.css
- addon/styles/global.css
- addon/styles/well.css
- docs/concepts/wells.md
> Image wells

- addon/styles/colors.css
- addon/styles/components/es-footer.css
- addon/styles/components/es-header.css
- addon/styles/global.css
Plain old text links; now with a nice 3dp soft underline and a good contrasting color. 
Re #241
> Link styling

- addon/styles/components/es-button.css
- addon/styles/components/es-footer.css
- addon/styles/components/es-header.css
- addon/styles/global.css
- addon/styles/well.css
This should keep the fancy fat lines contained.
Closes #255
> Scope fancy link styling to site `<main>`

- addon/styles/global.css
> Add custom property for mono font stack

- addon/components/es-footer.js
- addon/components/es-header.js
- addon/constants/es-footer.js
- addon/templates/components/es-footer.hbs
- addon/templates/components/es-header.hbs
- package-lock.json
- package.json
This is required as a first step for https://github.com/ember-learn/ember-website/issues/457 so that internal links won't redirect to the production website 🎉
> Fix navbar and footer link overrides

- addon/styles/colors.css
- addon/styles/components/es-button.css
- addon/styles/components/es-header.css
- addon/styles/global.css
- addon/templates/components/es-button.hbs
- docs/components/button.md
- tests/integration/components/es-button-test.js
Closes #265 
Closes #264 
Closes #241
> Add styling for link buttons

- public/images/boxes-bottom-continued.svg
- public/images/swipe-top.svg
Fixes https://github.com/ember-learn/ember-styleguide/issues/266
Fixes https://github.com/ember-learn/ember-styleguide/issues/268
> SVG adjustments

- addon/styles/background-shapes.css
- addon/styles/components/es-card.css
- addon/templates/components/es-page-header.hbs
- docs/components/page-header.md
- index.js
- package-lock.json
- package.json
- public/images/swipe-top.svg
Fixes https://github.com/ember-learn/ember-styleguide/issues/272
> Minor improvements

- addon/components/es-card-content.js
- addon/components/es-link-card.js
- addon/styles/addon.css
- addon/styles/backgrounds.css
- addon/styles/components/es-card.css
- addon/styles/global.css
- addon/templates/components/es-card-content.hbs
- addon/templates/components/es-card.hbs
- addon/templates/components/es-link-card.hbs
- app/components/es-card-content.js
- app/components/es-link-card.js
- app/templates/components/es-card-content.js
- app/templates/components/es-link-card.js
- EsCard (vertical, icon or full sized image)
- EsLinkCard (linked, icon, horizontal)
Re #276
> Separate EsCard

- addon/styles/backgrounds.css
- docs/css/helpers.md
Fixes https://github.com/ember-learn/ember-styleguide/issues/294
> fix bg-none css helper

- addon/templates/components/es-header.hbs
As mentioned in https://github.com/ember-learn/empress-blog-ember-template/issues/43#issuecomment-631988953
> Add an aria-label to the primary nav element

- tests/dummy/config/environment.js
Took my first look at the repo / Netlify.
> Add README link

- addon/styles/components/es-footer.css
- addon/styles/global.css
- docs/css/global.md
Added the styling specified in the design in #329 
Fixes #329
> Add styling for <hr/>

- addon/styles/typography.css
- there are some header tag spacing issues described in https://github.com/ember-learn/ember-styleguide/pull/335
- this attempts to remove header header tag specific styling that may be appropriate for the main website, but may not be appropriate for the blog posts
Co-Authored-By: Chris Manson <mansona@users.noreply.github.com>
> fix header spacing

- addon/components/es-footer-help.js
- addon/templates/components/es-footer-help.hbs
- addon/templates/components/es-footer.hbs
- app/components/es-footer-help.js
- app/templates/components/es-footer-help.js
- docs/components/footer.md
> contact details in footer

- addon/styles/global.css
I think this amounts to a 1px change so it should be fine to release in a patch 👍
> using a spacing variable for hr margin

- addon/templates/components/es-footer-help.hbs
Fix typo in email address / subject line for footer template issue #357
> fix issues-357 email link

- package-lock.json
- package.json
- tests/dummy/app/index.html
- tests/dummy/config/environment.js
> Upgrade field-guide to v1.4.0

- addon/templates/components/es-button.hbs
- addon/templates/components/es-header.hbs
Since `hasBlock` will be deprecated soon.
> Use has-block helper

- addon/constants/links.js
https://github.com/ember-learn/ember-styleguide/issues/372
> Update the link to the guides to include release

- package-lock.json
- package.json
> Remove ember-on-modifier

- addon/styles/sidebar-container.css
> fix sidebar shrinking in certain cases when there's content next to it

- .github/workflows/ci.yml
This is simplifying the github-ci file a lot. It is the same set of changes that were added in https://github.com/ember-learn/guidemaker-ember-template/pull/81 and I'm just migrating them to the styleguide now 👍
> simplifying github ci file

- addon/styles/helpers/flex.css
- docs/css/helpers.md
Fixes #283 
Adds flex-helper classes and documented the already present one
> Flex helper classes

- addon/components/es-pagination.hbs
- addon/styles/addon.css
- addon/styles/components/es-pagination.css
- app/components/es-pagination.js
- docs/components/pagination.md
- package-lock.json
- package.json
- tests/integration/components/es-pagination-test.js
> Adds pagination component to the styleguide

- addon/styles/components/es-sidebar.css
- addon/styles/sidebar-container.css
- docs/components/sidebar.md
- tests/integration/components/es-sidebar-test.js
Because of the PR for guide maker it's easier to increase the width here so the media queries work all there :)
> Increase width sidebar

- .github/workflows/gh-pages.yml
I recently released a new format of the lint-to-the-future dashboard action, and this requires a slight update 👍
> use new lint-to-the-future dashboard action

- addon/constants/links.js
- https://github.com/ember-learn/ember-website/pull/1162
- https://github.com/ember-learn/ember-website/pull/1161
> Add new support page links

- package.json
- pnpm-lock.yaml
The commit on this PR has a very strange name on purpose. release-plan looks for  commits with the format `Merge Pull Request #number ...` and if it doesn't find a commit like that then the PR won't be included in the release 😞
> Update release plan and fix latest release
